### ISSUE TITLE
Debug: logOut() call results in IO exception

### ISSUE THREAD

**Issue by acleland** [knox4/Team8#29]
Whenever I call conn.logOut, I get the following IO exception:

java.io.IOException: Connection is not open

Maybe this is what is supposed to happen, but it seems like we shouldn't have to see an exception message every time we log out.

**Comment by knox4** [comment]
What part of your code is using logOut? The reason it's throwing an
IOException, if I'm not mistaken, is because logOut was written before the
disconnect function, which is called per function in order to not tie up
resources that aren't being used. The latest version of the program that
I'm looking at has no calls to logOut anymore; I believe that function can
be safely commented out in lieu of disconnect unless I'm missing something.

**Comment by knox4** [comment]
To clarify - it's happening because logout is attempting this: 

try {
            ftpClient.logout();
        }
        catch (IOException e) {
            e.printStackTrace();
        }

But disconnect() has already called ftpclient.logout, so logOut is printing the stack trace indicated by the catch. It's harmless for it to do so, but you could just remove the e.printStackTrace() part if you didn't want to comment out that code completely.

**Comment by acleland** [comment]
Oh, ok. I get how it is working now. I didn't know about disconnect(). Actually, though I think in my case, I was calling logOut when I hadn't even established a connection yet. Thanks, Gene.

**Comment by knox4** [comment]
No problem. Honestly I suspect it's my fault anyway - I was refactoring my
code to avoid duplication and one of my refactors was disconnect - I am not
CERTAIN if logOut existed prior to that, but it probably did, and I wasn't
using it. But then other people's functions also started using disconnect,
so whoever wrote that bit... My bad. :)
